---
# Playbook to build Fabric baseimage for arbitrary distributions

- hosts: localhost
  connection: local
  roles:
   - install-deps
   - install-golang
   - install-java
   - install-protobuf
   - install-node
   - validate
