---
# Starts container of the type {{disto}}
#  then installs the packaged dependencies for that distro

- name: Set dependencies for Ubuntu
  set_fact:
    deps_cmd: "{{ ubuntu_deps_cmd }}"
  when: distro == "ubuntu"

- name: Set dependencies for Centos
  set_fact:
    deps_cmd: "{{ centos_deps_cmd }}"
  when: distro == "centos"

- name: "Create docker build directory"
  file:
    path: /tmp/fabric-baseimage
    state: directory

- name: "Template Dockerfile"
  template:
    src: Dockerfile.j2
    dest: /tmp/fabric-baseimage/Dockerfile

- name: "Build {{ distro }} docker image with dependencies"
  docker_image:
    path: /tmp/fabric-baseimage/
    name: fabric-baseimage-in-progress
    state: present
